export enum Alertas {
  iniciarSesion = 'Has iniciado sesión correctamente.',
  cerrarSesion = 'Has cerrado sesión correctamente.',
  errorSesion = 'Usuario o contraseña incorrectos.',
  contrasenaOlvidada = 'Si no recuerdas la contraseña contacta con el administrador.',
  itemAgregar = 'Item agregado correctamente.',
  itemEliminar = 'Item eliminado correctamente.',
  itemEditar = 'Item editado correctamente.',
  guardarCambios = 'Cambios guardados.',
  cancelarEdicion = 'Edición cancelada.',
  editarItem = 'Editando sección.',
  porcentajeError = 'No puedes colocar porcentajes superiores al 100%.',
  errorRender = 'Render desactiva la api por inactividad, espera dos minutos y vuelve a intentarlo. Sino contactame.',
  imagenActualizada = 'Imagen actualizada correctamente.',
  imagenSubida = 'Imagen subida correctamente.',
  imagenEliminada = 'Imagen eliminada correctamente.',
}
